printWidth: 140
tabWidth: 4
arrowParens: 'avoid'
useTabs: false
bracketSpacing: true
singleQuote: true
jsxBracketSameLine: true
htmlWhitespaceSensitivity: 'css'
endOfLine: 'auto'
overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.html'
      - '*.scss'
    options:
      tabWidth: 2
trailingComma: none
