SofluxUsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: SofluxUsersTable-${opt:stage, 'dev'}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
        - AttributeName: id
          KeyType: HASH
